// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEcologicCrowsourcingApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyEcologicCrowsourcingApp.Migrations
{
    [DbContext(typeof(EcologicDbContext))]
    [Migration("20251003194151_AddPointDechetTable")]
    partial class AddPointDechetTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CarburantEstime")
                        .HasColumnType("double precision");

                    b.Property<double>("DistanceTotale")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("DureeEstimee")
                        .HasColumnType("interval");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapaciteVehicule")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<Guid>>("ListePointsIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("TempsMaxParTrajet")
                        .HasColumnType("interval");

                    b.Property<string>("ZoneGeographique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("OptimisationRequests");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItineraireOptimiseeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptimisationRequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("ScoreEfficacite")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireOptimiseeId");

                    b.HasIndex("OptimisationRequestId")
                        .IsUnique();

                    b.ToTable("OptimisationResults");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NbrVolontaires")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VehiculeId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganisationId");

                    b.HasIndex("VehiculeId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItineraireId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("VolumeEstime")
                        .HasColumnType("double precision");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireId");

                    b.HasIndex("UserId");

                    b.ToTable("PointDechets");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Vehicule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapaciteMax")
                        .HasColumnType("double precision");

                    b.Property<double>("CarburantConsommation")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("VitesseMoyenne")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Itineraires")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationRequest", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationResult", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Itineraire", "ItineraireOptimisee")
                        .WithMany()
                        .HasForeignKey("ItineraireOptimiseeId");

                    b.HasOne("MyEcologicCrowsourcingApp.Models.OptimisationRequest", "OptimisationRequest")
                        .WithOne()
                        .HasForeignKey("MyEcologicCrowsourcingApp.Models.OptimisationResult", "OptimisationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraireOptimisee");

                    b.Navigation("OptimisationRequest");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Vehicule", "Vehicule")
                        .WithMany()
                        .HasForeignKey("VehiculeId");

                    b.Navigation("Vehicule");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Itineraire", null)
                        .WithMany("ListePoints")
                        .HasForeignKey("ItineraireId");

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.Navigation("ListePoints");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.Navigation("Itineraires");
                });
#pragma warning restore 612, 618
        }
    }
}
