// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEcologicCrowsourcingApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyEcologicCrowsourcingApp.Migrations
{
    [DbContext(typeof(EcologicDbContext))]
    partial class EcologicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChallengesRequired")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Criteria")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PointsRequired")
                        .HasColumnType("integer");

                    b.Property<int?>("SpecificType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AIGeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AIPromptUsed")
                        .HasColumnType("text");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentParticipants")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSubmissionsPerUser")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredProofType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Tips")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationCriteria")
                        .HasColumnType("text");

                    b.Property<int>("VerificationMethod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("StartDate");

                    b.HasIndex("Type");

                    b.HasIndex("IsActive", "Type", "StartDate");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.ChallengeSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AIConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AIVerificationResult")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AIVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAIVerified")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProofUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("UserId", "ChallengeId");

                    b.ToTable("ChallengeSubmissions");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.ChallengeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AIPromptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPoints")
                        .HasColumnType("integer");

                    b.Property<int>("MinPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationCriteriaTemplate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Type");

                    b.ToTable("ChallengeTemplates");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.CommentReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "EstActif");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.ForumCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ForumCategories");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CarburantEstime")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceTotale")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("DureeEstimee")
                        .HasColumnType("interval");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("OrganisationId", "Statut");

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapaciteVehicule")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<Guid>>("ListePointsIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("TempsMaxParTrajet")
                        .HasColumnType("interval");

                    b.Property<string>("ZoneGeographique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("OptimisationRequests");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItineraireOptimiseeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptimisationRequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("ScoreEfficacite")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireOptimiseeId");

                    b.HasIndex("OptimisationRequestId")
                        .IsUnique();

                    b.ToTable("OptimisationResults");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NbrVolontaires")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RepresentantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehiculeId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganisationId");

                    b.HasIndex("RepresentantId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateNettoyage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItineraireId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<Guid?>("NettoyeParOrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("VolumeEstime")
                        .HasColumnType("double precision");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireId");

                    b.HasIndex("NettoyeParOrganisationId");

                    b.HasIndex("Statut");

                    b.HasIndex("UserId");

                    b.HasIndex("Zone");

                    b.HasIndex("Statut", "Zone");

                    b.ToTable("PointDechets");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPinned");

                    b.HasIndex("UserId");

                    b.HasIndex("CategoryId", "IsPinned", "CreatedAt");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PostReaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("PostReactions");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PostReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PostId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("PostReports");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.RecommandationEcologique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionRecommandee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContexteUtilise")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PointDechetId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScorePriorite")
                        .HasColumnType("integer");

                    b.Property<string>("Urgence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DateGeneration");

                    b.HasIndex("PointDechetId");

                    b.ToTable("RecommandationsEcologiques");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.SubmissionVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SubmissionId", "UserId")
                        .IsUnique();

                    b.ToTable("SubmissionVotes");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.UserChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("UserId", "ChallengeId")
                        .IsUnique();

                    b.ToTable("UserChallenges");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.UserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChallengesCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("ChallengesInProgress")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<int>("GlobalRank")
                        .HasColumnType("integer");

                    b.Property<int>("IdentificationChallenges")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastChallengeCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LitterPickupChallenges")
                        .HasColumnType("integer");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyRank")
                        .HasColumnType("integer");

                    b.Property<int>("PlantingChallenges")
                        .HasColumnType("integer");

                    b.Property<int>("RecyclingChallenges")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionsApproved")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionsRejected")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeeklyRank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GlobalRank");

                    b.HasIndex("TotalPoints");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStats");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Vehicule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapaciteMax")
                        .HasColumnType("double precision");

                    b.Property<double>("CarburantConsommation")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DerniereUtilisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("VitesseMoyenne")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "EstDisponible");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Challenge", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.ChallengeSubmission", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Challenge", "Challenge")
                        .WithMany("Submissions")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("ReviewedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Comment", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyEcologicCrowsourcingApp.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.CommentReaction", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Depot", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Depots")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Itineraires")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationRequest", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationResult", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Itineraire", "ItineraireOptimisee")
                        .WithMany()
                        .HasForeignKey("ItineraireOptimiseeId");

                    b.HasOne("MyEcologicCrowsourcingApp.Models.OptimisationRequest", "OptimisationRequest")
                        .WithOne()
                        .HasForeignKey("MyEcologicCrowsourcingApp.Models.OptimisationResult", "OptimisationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraireOptimisee");

                    b.Navigation("OptimisationRequest");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "Representant")
                        .WithMany()
                        .HasForeignKey("RepresentantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Representant");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Itineraire", null)
                        .WithMany("ListePoints")
                        .HasForeignKey("ItineraireId");

                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "NettoyeParOrganisation")
                        .WithMany()
                        .HasForeignKey("NettoyeParOrganisationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NettoyeParOrganisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Post", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.ForumCategory", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PostReaction", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PostReport", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Post", "Post")
                        .WithMany("Reports")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "ReportedBy")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");

                    b.Navigation("ReportedBy");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.RecommandationEcologique", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.PointDechet", "PointDechet")
                        .WithMany("Recommandations")
                        .HasForeignKey("PointDechetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointDechet");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.SubmissionVote", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.ChallengeSubmission", "Submission")
                        .WithMany("Votes")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.User", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Users")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.UserAchievement", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.UserChallenge", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Challenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany("UserChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.UserStats", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("MyEcologicCrowsourcingApp.Models.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Vehicule", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Vehicules")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Challenge", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.ChallengeSubmission", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Comment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.ForumCategory", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.Navigation("ListePoints");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.Navigation("Depots");

                    b.Navigation("Itineraires");

                    b.Navigation("Users");

                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.Navigation("Recommandations");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Stats");

                    b.Navigation("Submissions");

                    b.Navigation("UserChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
