// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEcologicCrowsourcingApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyEcologicCrowsourcingApp.Migrations
{
    [DbContext(typeof(EcologicDbContext))]
    partial class EcologicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "EstActif");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CarburantEstime")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceTotale")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("DureeEstimee")
                        .HasColumnType("interval");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("OrganisationId", "Statut");

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapaciteVehicule")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<Guid>>("ListePointsIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("TempsMaxParTrajet")
                        .HasColumnType("interval");

                    b.Property<string>("ZoneGeographique")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("OptimisationRequests");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItineraireOptimiseeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OptimisationRequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("ScoreEfficacite")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireOptimiseeId");

                    b.HasIndex("OptimisationRequestId")
                        .IsUnique();

                    b.ToTable("OptimisationResults");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NbrVolontaires")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RepresentantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehiculeId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganisationId");

                    b.HasIndex("RepresentantId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateNettoyage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItineraireId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("double precision");

                    b.Property<Guid?>("NettoyeParOrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("VolumeEstime")
                        .HasColumnType("double precision");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireId");

                    b.HasIndex("NettoyeParOrganisationId");

                    b.HasIndex("Statut");

                    b.HasIndex("UserId");

                    b.HasIndex("Zone");

                    b.HasIndex("Statut", "Zone");

                    b.ToTable("PointDechets");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.RecommandationEcologique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionRecommandee")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContexteUtilise")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PointDechetId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScorePriorite")
                        .HasColumnType("integer");

                    b.Property<string>("Urgence")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DateGeneration");

                    b.HasIndex("PointDechetId");

                    b.ToTable("RecommandationsEcologiques");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Vehicule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CapaciteMax")
                        .HasColumnType("double precision");

                    b.Property<double>("CarburantConsommation")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DerniereUtilisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<double>("VitesseMoyenne")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId", "EstDisponible");

                    b.ToTable("Vehicules");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Depot", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Depots")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Itineraires")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationRequest", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.OptimisationResult", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Itineraire", "ItineraireOptimisee")
                        .WithMany()
                        .HasForeignKey("ItineraireOptimiseeId");

                    b.HasOne("MyEcologicCrowsourcingApp.Models.OptimisationRequest", "OptimisationRequest")
                        .WithOne()
                        .HasForeignKey("MyEcologicCrowsourcingApp.Models.OptimisationResult", "OptimisationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraireOptimisee");

                    b.Navigation("OptimisationRequest");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "Representant")
                        .WithMany()
                        .HasForeignKey("RepresentantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Representant");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Itineraire", null)
                        .WithMany("ListePoints")
                        .HasForeignKey("ItineraireId");

                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "NettoyeParOrganisation")
                        .WithMany()
                        .HasForeignKey("NettoyeParOrganisationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyEcologicCrowsourcingApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NettoyeParOrganisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.RecommandationEcologique", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.PointDechet", "PointDechet")
                        .WithMany("Recommandations")
                        .HasForeignKey("PointDechetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointDechet");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.User", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Users")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Vehicule", b =>
                {
                    b.HasOne("MyEcologicCrowsourcingApp.Models.Organisation", "Organisation")
                        .WithMany("Vehicules")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Itineraire", b =>
                {
                    b.Navigation("ListePoints");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.Organisation", b =>
                {
                    b.Navigation("Depots");

                    b.Navigation("Itineraires");

                    b.Navigation("Users");

                    b.Navigation("Vehicules");
                });

            modelBuilder.Entity("MyEcologicCrowsourcingApp.Models.PointDechet", b =>
                {
                    b.Navigation("Recommandations");
                });
#pragma warning restore 612, 618
        }
    }
}
